// Auto-generated by flagsc. DO NOT EDIT.
#pragma once
#include <string>

namespace forge {

struct Flags {
    const char *output;  // string, required
    bool        output_set;
    int         count;  // int, default: 1
    bool        count_set;
    long        threshold;  // long, default: 0
    bool        threshold_set;
};

void FlagsInit( Flags *flags );
bool FlagsParse( Flags *flags, int argc, char **argv, std::string *err_msg );
bool FlagsValidate( const Flags *flags, std::string *err_msg );

}  // namespace forge
