#include "codegen.h"

#include <cstring>

namespace forge {

namespace {

static const char kGeneratedIntMin[] = "-2147483648";
static const char kGeneratedIntMax[] = "2147483647";

static const char *
CppType( FlagType t )
{
    switch ( t ) {
    case FLAG_TYPE_STRING:
        return "const char *";
    case FLAG_TYPE_INT:
        return "int";
    case FLAG_TYPE_LONG:
        return "long";
    }
    return "int";
}

static const char *
TypeComment( const FlagSpec *s )
{
    switch ( s->type ) {
    case FLAG_TYPE_STRING:
        return "string";
    case FLAG_TYPE_INT:
        return "int";
    case FLAG_TYPE_LONG:
        return "long";
    }
    return "";
}

static void
WriteHeader( const FlagDef *def, const char *basename, FILE *out_h )
{
    fprintf( out_h, "// Auto-generated by flagsc. DO NOT EDIT.\n" );
    fprintf( out_h, "#pragma once\n" );
    fprintf( out_h, "#include <string>\n" );
    fprintf( out_h, "\n" );
    fprintf( out_h, "namespace forge {\n" );
    fprintf( out_h, "\n" );
    fprintf( out_h, "struct Flags {\n" );

    for ( int i = 0; i < def->count; i++ ) {
        const FlagSpec *s        = &def->specs[i];
        const char     *ctype    = CppType( s->type );
        const char     *tcomment = TypeComment( s );

        if ( s->has_default ) {
            fprintf( out_h, "  %-16s %s;  // %s, default: %s\n", ctype, s->name,
                     tcomment, s->default_str );
        } else if ( s->required ) {
            fprintf( out_h, "  %-16s %s;  // %s, required\n", ctype, s->name,
                     tcomment );
        } else {
            fprintf( out_h, "  %-16s %s;  // %s\n", ctype, s->name, tcomment );
        }
        fprintf( out_h, "  bool            %s_set;\n", s->name );
    }

    fprintf( out_h, "};\n" );
    fprintf( out_h, "\n" );
    fprintf( out_h, "void FlagsInit(Flags *flags);\n" );
    fprintf( out_h,
             "bool FlagsParse(Flags *flags, int argc, char **argv, std::string "
             "*err_msg);\n" );
    fprintf(
        out_h,
        "bool FlagsValidate(const Flags *flags, std::string *err_msg);\n" );
    fprintf( out_h, "\n" );
    fprintf( out_h, "} // namespace forge\n" );

    (void)basename;
}

static void
WriteSource( const FlagDef *def, const char *basename, FILE *out_cc )
{
    // Use only the filename portion for the #include (strip any directory
    // prefix)
    const char *include_name = strrchr( basename, '/' );
    include_name             = include_name ? include_name + 1 : basename;

    fprintf( out_cc, "// Auto-generated by flagsc. DO NOT EDIT.\n" );
    fprintf( out_cc, "#include \"%s.h\"\n", include_name );
    fprintf( out_cc, "\n" );
    fprintf( out_cc, "#include <cerrno>\n" );
    fprintf( out_cc, "#include <cstdlib>\n" );
    fprintf( out_cc, "#include <cstring>\n" );
    fprintf( out_cc, "\n" );
    fprintf( out_cc, "namespace forge {\n" );
    fprintf( out_cc, "\n" );

    // FlagsInit
    fprintf( out_cc, "void FlagsInit(Flags *flags) {\n" );
    for ( int i = 0; i < def->count; i++ ) {
        const FlagSpec *s = &def->specs[i];
        if ( s->has_default ) {
            switch ( s->type ) {
            case FLAG_TYPE_STRING:
                fprintf( out_cc,
                         "  flags->%s = \"%s\"; flags->%s_set = false;\n",
                         s->name, s->default_str, s->name );
                break;
            case FLAG_TYPE_INT:
                fprintf( out_cc, "  flags->%s = %s; flags->%s_set = false;\n",
                         s->name, s->default_str, s->name );
                break;
            case FLAG_TYPE_LONG:
                fprintf( out_cc, "  flags->%s = %sL; flags->%s_set = false;\n",
                         s->name, s->default_str, s->name );
                break;
            }
        } else {
            switch ( s->type ) {
            case FLAG_TYPE_STRING:
                fprintf( out_cc, "  flags->%s = \"\"; flags->%s_set = false;\n",
                         s->name, s->name );
                break;
            case FLAG_TYPE_INT:
                fprintf( out_cc, "  flags->%s = 0; flags->%s_set = false;\n",
                         s->name, s->name );
                break;
            case FLAG_TYPE_LONG:
                fprintf( out_cc, "  flags->%s = 0L; flags->%s_set = false;\n",
                         s->name, s->name );
                break;
            }
        }
    }
    fprintf( out_cc, "}\n" );
    fprintf( out_cc, "\n" );

    // FlagsParse
    fprintf( out_cc,
             "bool FlagsParse(Flags *flags, int argc, char **argv, std::string "
             "*err_msg) {\n" );
    fprintf( out_cc, "  for (int i = 1; i < argc; i++) {\n" );

    bool first = true;
    for ( int i = 0; i < def->count; i++ ) {
        const FlagSpec *s    = &def->specs[i];
        const char     *elif = first ? "if" : "} else if";
        first                = false;

        fprintf( out_cc, "    %s (strcmp(argv[i], \"--%s\") == 0) {\n", elif,
                 s->name );
        fprintf( out_cc, "      if (i + 1 >= argc) {\n" );
        fprintf(
            out_cc,
            "        *err_msg = std::string(\"flag --%s requires a value\");\n",
            s->name );
        fprintf( out_cc, "        return true;\n" );
        fprintf( out_cc, "      }\n" );

        switch ( s->type ) {
        case FLAG_TYPE_STRING:
            fprintf( out_cc, "      flags->%s = argv[++i];\n", s->name );
            fprintf( out_cc, "      flags->%s_set = true;\n", s->name );
            break;
        case FLAG_TYPE_INT:
            fprintf( out_cc, "      char *end_%s;\n", s->name );
            fprintf( out_cc,
                     "      long val_%s = strtol(argv[i + 1], &end_%s, 10);\n",
                     s->name, s->name );
            fprintf( out_cc, "      if (*end_%s != '\\0') {\n", s->name );
            fprintf( out_cc,
                     "        *err_msg = std::string(\"flag --%s: invalid int: "
                     "\") + argv[i + 1];\n",
                     s->name );
            fprintf( out_cc, "        return true;\n" );
            fprintf( out_cc, "      }\n" );
            fprintf( out_cc, "      if (val_%s < %sL || val_%s > %sL) {\n",
                     s->name, kGeneratedIntMin, s->name, kGeneratedIntMax );
            fprintf( out_cc,
                     "        *err_msg = std::string(\"flag --%s: value out of "
                     "int range: \") + argv[i + 1];\n",
                     s->name );
            fprintf( out_cc, "        return true;\n" );
            fprintf( out_cc, "      }\n" );
            fprintf( out_cc, "      flags->%s = (int)val_%s;\n", s->name,
                     s->name );
            fprintf( out_cc, "      flags->%s_set = true;\n", s->name );
            fprintf( out_cc, "      i++;\n" );
            break;
        case FLAG_TYPE_LONG:
            fprintf( out_cc, "      char *end_%s;\n", s->name );
            fprintf( out_cc, "      errno = 0;\n" );
            fprintf( out_cc,
                     "      long val_%s = strtol(argv[i + 1], &end_%s, 10);\n",
                     s->name, s->name );
            fprintf( out_cc, "      if (*end_%s != '\\0' || errno != 0) {\n",
                     s->name );
            fprintf( out_cc,
                     "        *err_msg = std::string(\"flag --%s: invalid "
                     "long: \") + argv[i + 1];\n",
                     s->name );
            fprintf( out_cc, "        return true;\n" );
            fprintf( out_cc, "      }\n" );
            fprintf( out_cc, "      flags->%s = val_%s;\n", s->name, s->name );
            fprintf( out_cc, "      flags->%s_set = true;\n", s->name );
            fprintf( out_cc, "      i++;\n" );
            break;
        }
    }

    if ( !first ) {
        fprintf( out_cc, "    } else {\n" );
        fprintf(
            out_cc,
            "      *err_msg = std::string(\"unknown flag: \") + argv[i];\n" );
        fprintf( out_cc, "      return true;\n" );
        fprintf( out_cc, "    }\n" );
    } else {
        fprintf( out_cc, "    (void)argv;\n" );
    }

    fprintf( out_cc, "  }\n" );
    fprintf( out_cc, "  return false;\n" );
    fprintf( out_cc, "}\n" );
    fprintf( out_cc, "\n" );

    // FlagsValidate
    fprintf(
        out_cc,
        "bool FlagsValidate(const Flags *flags, std::string *err_msg) {\n" );
    bool has_required = false;
    for ( int i = 0; i < def->count; i++ ) {
        if ( def->specs[i].required ) {
            has_required = true;
            break;
        }
    }
    if ( !has_required ) {
        fprintf( out_cc, "  (void)flags;\n" );
        fprintf( out_cc, "  (void)err_msg;\n" );
    }
    for ( int i = 0; i < def->count; i++ ) {
        const FlagSpec *s = &def->specs[i];
        if ( s->required ) {
            fprintf( out_cc, "  if (!flags->%s_set) {\n", s->name );
            fprintf( out_cc,
                     "    *err_msg = \"required flag --%s not provided\";\n",
                     s->name );
            fprintf( out_cc, "    return true;\n" );
            fprintf( out_cc, "  }\n" );
        }
    }
    fprintf( out_cc, "  return false;\n" );
    fprintf( out_cc, "}\n" );
    fprintf( out_cc, "\n" );
    fprintf( out_cc, "} // namespace forge\n" );
}

}  // namespace

bool
CodegenWrite( const FlagDef *def, const char *basename, FILE *out_h,
              FILE *out_cc, std::string *err_msg )
{
    WriteHeader( def, basename, out_h );
    WriteSource( def, basename, out_cc );
    (void)err_msg;
    return false;
}

}  // namespace forge
