[package]
name = "ffi_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
cty = "0.2.2"

[lib]
name = "ffi"
# crate-type = ["cdylib"]      # Creates dynamic lib
crate-type = ["staticlib"] # Creates static lib
